package com.education.lbjt.game.actors.scroll.tutorial

import com.badlogic.gdx.graphics.g2d.Animation
import com.education.lbjt.R
import com.education.lbjt.game.actors.scroll.tutorial.AAbstractTutorialScrollPanel.Static.LabelFont
import com.education.lbjt.game.actors.scroll.tutorial.AAbstractTutorialScrollPanel.Static.Space
import com.education.lbjt.game.actors.scroll.tutorial.AAbstractTutorialScrollPanel.Static.TypingLabelFontFamily
import com.education.lbjt.game.actors.scroll.VerticalGroup
import com.education.lbjt.game.actors.scroll.tutorial.AAbstractTutorialScrollPanel.Static.CodePanelHeight
import com.education.lbjt.game.actors.scroll.tutorial.actors.AAbstractList
import com.education.lbjt.game.manager.util.SpriteUtil
import com.education.lbjt.game.utils.GameColor
import com.education.lbjt.game.utils.advanced.AdvancedScreen

class AScrollPanel_GeneralInformation(
    _screen: AdvancedScreen,
    private val spriteUtil: SpriteUtil.GeneralInformation
): AAbstractTutorialScrollPanel(_screen) {

    override fun VerticalGroup.addActorsOnVerticalGroup() {
        addImage(spriteUtil.I1, 620f)
        addSpace(Space._80)
        addLabel(R.string.geninfo_title_1, LabelFont.Inter_ExtraBold_50, GameColor.textRed)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_1, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_1, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_2, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_Label(R.array.geninfo_arr_1, AAbstractList.Static.Align.Center)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_3, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_2, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_4, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_Label(R.array.geninfo_arr_2)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_note_1, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_Label(R.array.geninfo_arr_3)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_note_2, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_1)
        addSpace(Space._25)
        addImage(spriteUtil.I2, 392f)
        addSpace(Space._25)
        addLabel(R.string.geninfo_title_2, LabelFont.Inter_ExtraBold_50, GameColor.textRed)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_5, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_Label(R.array.geninfo_arr_4)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_2)
        addSpace(Space._80)
        addLabel(R.string.geninfo_sub_title_1, LabelFont.Inter_Regular_35, GameColor.textRed)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_6, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_note_3, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I3, 396f)
        addSpace(Space._80)
        addLabel(R.string.geninfo_sub_title_2, LabelFont.Inter_Regular_35, GameColor.textRed)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_3)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_7, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I4, 392f)
        addSpace(Space._80)
        addTypingLabel(R.string.geninfo_text_8, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_3, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_9, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I5, 392f)
        addSpace(Space._80)
        addTypingLabel(R.string.geninfo_text_10, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I6, 392f)
        addSpace(Space._80)
        addLabel(R.string.geninfo_title_3, LabelFont.Inter_ExtraBold_50, GameColor.textRed)
        addSpace(Space._25)
        addImage(spriteUtil.I7, 457f)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_11, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_TypingLabel(R.array.geninfo_arr_5, symbol = AAbstractList.Static.Symbol.Bullet)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_12, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_4, CodePanelHeight._110)
        addSpace(Space._25)
        addImage(spriteUtil.I8, 456f)
        addSpace(Space._80)
        addTypingLabel(R.string.geninfo_text_13, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I9, 328f)
        addSpace(Space._80)
        addTypingLabel(R.string.geninfo_text_14, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_TypingLabel(R.array.geninfo_arr_6, symbol = AAbstractList.Static.Symbol.Number)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_5, CodePanelHeight._400)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_4)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_15, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I10, 392f)
        addSpace(Space._80)
        addLabel(R.string.geninfo_sub_title_3, LabelFont.Inter_Regular_35, GameColor.textRed)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_16, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_TypingLabel(R.array.geninfo_arr_7, symbol = AAbstractList.Static.Symbol.Number)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_17, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I9, 328f)
        addSpace(Space._80)
        addCodePanel(R.string.geninfo_codepanel_6, CodePanelHeight._400)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_5)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_18, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addLongQuote(R.string.geninfo_longquote_6)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_19, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I9, 328f)
        addSpace(Space._80)
        addTypingLabel(R.string.geninfo_text_20, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_7, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_21, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_8, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_22, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_9, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_23, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_10, CodePanelHeight._110)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_24, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImage(spriteUtil.I11, 421f)
        addSpace(Space._80)
        addLongQuote(R.string.geninfo_longquote_7)
        addSpace(Space._80)
        addLabel(R.string.geninfo_title_5, LabelFont.Inter_ExtraBold_50, GameColor.textRed)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_25, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addList_TypingLabel(R.array.geninfo_arr_8, symbol = AAbstractList.Static.Symbol.Bullet)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_26, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addCodePanel(R.string.geninfo_codepanel_11, CodePanelHeight._400)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_note_4, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addTypingLabel(R.string.geninfo_text_27, TypingLabelFontFamily.Inter_MediumBold_30)
        addSpace(Space._25)
        addImageAnim(0.033f, spriteUtil.animObama, Animation.PlayMode.LOOP, 460f)
        addSpace(Space._80)
        addTypingLabel(R.string.main_source_info, LabelFont.Inter_Regular_35)
        addSpace(Space._25)
        addTypingLabel(R.string.PS_Vel_daN, LabelFont.Inter_Black_30)
        addSpace(Space._80)
    }

}